name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git cmake zip unzip openjdk-11-jdk autoconf libtool pkg-config
          pip3 install --user buildozer cython==0.29.33
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Fix libtool macros
        run: |
          sudo apt-get install -y libtool pkg-config automake
          # Надёжный поиск директории с макросами libtool
          LIBTOOL_M4_DIR=$(sudo find /usr/share -name "libtool.m4" -exec dirname {} \; 2>/dev/null | head -n 1)
          if [ -n "$LIBTOOL_M4_DIR" ]; then
            sudo cp "$LIBTOOL_M4_DIR"/*.m4 /usr/share/aclocal/
          fi

      - name: Build with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
